version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
  todo-app:
    image: gotify/server:latest
    ports:
      - "8080:8080"
    volumes:
      - gotify_data:/app/data
volumes:
  gotify_data: